apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 1  # Number of pods to run
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080  # Port your app runs on inside the container
          resources:
            requests:
              memory: "100Mi"
              cpu: "0.1"
            limits:
              memory: "200Mi"
              cpu: "0.2"
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
