apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80         # The port to expose inside the AKS cluster
      targetPort: 8080  # The port your app is listening to in the container
  type: LoadBalancer   # Exposes the service externally with an external IP
