name: Java CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - '**'  # Run on push to any branch
  pull_request:
    branches:
      - '**'  # Run on pull request to any branch

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      build-tool: ${{ steps.set-build-tool.outputs.build-tool }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect build tool
        id: set-build-tool
        run: |
          if [ -f "pom.xml" ]; then
            echo "build-tool=maven" >> $GITHUB_OUTPUT
          elif [ -f "build.gradle" ] || [ -f "build.gradle.kts" ]; then
            echo "build-tool=gradle" >> $GITHUB_OUTPUT
          else
            echo "No build tool detected" && exit 1
          fi

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Lint with Checkstyle (Maven)
        continue-on-error: true
        if: needs.setup.outputs.build-tool == 'maven'
        run: |
          mvn checkstyle:check

      - name: Lint with Checkstyle (Gradle)
        continue-on-error: true
        if: needs.setup.outputs.build-tool == 'gradle'
        run: |
          ./gradlew checkstyleMain checkstyleTest

  unit-test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run unit tests (Maven)
        if: needs.setup.outputs.build-tool == 'maven'
        run: |
          mvn test

      - name: Run unit tests (Gradle)
        if: needs.setup.outputs.build-tool == 'gradle'
        run: |
          ./gradlew test

  integration-test:
    needs:
      - unit-test
      - setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run integration tests (Maven)
        if: needs.setup.outputs.build-tool == 'maven'
        run: |
          mvn verify -P integration-test

      - name: Run integration tests (Gradle)
        if: needs.setup.outputs.build-tool == 'gradle'
        run: |
          ./gradlew integrationTest

  sonar-analysis:
    needs:
      - unit-test
      - integration-test
      - lint
      - setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache SonarQube
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Run SonarQube analysis (Maven)
        continue-on-error: true  # Allow pipeline to continue even if this fails
        if: needs.setup.outputs.build-tool == 'maven'
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
          -Dsonar.projectKey=amasovic_cicd_a2dfe93e-585b-4553-9c94-86c3024bce80 \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN

      - name: Run SonarQube analysis (Gradle)
        continue-on-error: true  # Allow pipeline to continue even if this fails
        if: needs.setup.outputs.build-tool == 'gradle'
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonar 
            -Dsonar.projectKey=$SONAR_PROJECT_KEY \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN



  security-scan:
    if: github.ref == 'refs/heads/main'
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Snyk
        run: |
          curl --compressed https://static.snyk.io/cli/latest/snyk-linux -o snyk
          chmod +x ./snyk

      - name: Snyk security scan
        continue-on-error: true  # Allow pipeline to continue even if this fails
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          ./snyk monitor --all-projects --org=20e9dee4-5f99-42d2-b969-e23183e592fe

  build-docker:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    needs:
      - unit-test
      - integration-test
      - lint
      - sonar-analysis
      - security-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure CLI
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        run: az acr login --name ${{ secrets.AZURE_ACR_NAME }}

      - id: vars
        run: |
          echo "sha_short=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
          echo "image_id=$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image to ACR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/${{ steps.vars.outputs.image_id }}:latest
            ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/${{ steps.vars.outputs.image_id }}:${{ steps.vars.outputs.sha_short }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          images: ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/${{ steps.vars.outputs.image_id }}:latest


      - name: Install kubelogin
        run: az aks install-cli --kubelogin

      - name: Log in to Azure Kubernetes Service (AKS)
        run: az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_AKS_NAME }}
  
      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
  
      - name: Verify AKS deployment
        run: kubectl rollout status deployment/my-app-deployment




        